### ISSUE TITLE
Default credentials

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/microsite#1]
Hi @pierorex,
I installed locally the microsite. It seems to be ok. But I cannot access the admin panel. 
What are the default credentials for admin login on the microsite? 

Also I found that there are default users with names and e-mails on the database, including my name. I think these should be removed.

I tried to change admin password by 
```
./manage.py changepassword admin
```
but it throws an error for django.core.management module missing. Possibly misconfiguration of env?

Thank you in advance.

**Comment by skarampatakis** [comment]
I found out that instead of ./manage.py i have to run python3 manage.py and the rest of the command to change the password. I believe it should be documented, because people with no experience with python like me, may have similar problems.

**Comment by pierorex** [comment]
Thank you for pointing that out @skarampatakis , I wasn't available these days, sorry about that
