### ISSUE TITLE
Datasets uploaded with custom pipelines are not available to choose

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/microsite#2]
Datasets uploaded through custom pipelines are not available for selection through the microsite admin panel. Is there a different setting we need to edit?

**Comment by pierorex** [comment]
You can set the OS_API variable through the docker-compose.yml file or inside the microsite-backend/settings.py file. The app will only load datasets available within that endpoint.

**Comment by skarampatakis** [comment]
It can be only OS API (Babagge) or even a compatible one like Rudolf? 
Is the same valid for the OS Viewer that wil be used?

**Comment by skarampatakis** [comment]
Any update on this?

**Comment by pierorex** [comment]
A compatible one like RUDOLF will work, as long as it truly resembles the same OS API version being used by the app.
The OS Viewer will work in the same way

**Comment by skarampatakis** [comment]
Great. So I beleive the default configuration for the microsite deployed on the server would be to use the RUDOLF API, since it includes datasets imported throught the packager and custom pipelines.

**Comment by pierorex** [comment]
You're right, though I think we are using the OS one on the server for demo purposes these couple of weeks.
