### ISSUE TITLE
More detailed viz configuration

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/microsite#3]
Currently microsite admins can only select Treemap as a viz for a particular dataset. It would be more useful to be able to define in better detail on how the viz will look like. Probably by preselecting dimensions, measures or hierarchies, filters etc. Or even the kind of the viz.

**Comment by pierorex** [comment]
@skarampatakis 
I just added the other visualizations from OS-Viewer to the list of available renderings. 
Setting a fixed initial view with a dimension, hierarchy, and measure is WIP.

**Comment by pierorex** [comment]
@skarampatakis 
The update to include configuring the initial dimension + measure is finished, you can try it out at your convenience.
